env:
  global:
language: node_js
node_js:
- 12
cache:
  yarn: true
script:
  - yarn lint
  - yarn build
# Deploy update to AMO on tagged builds
deploy:
  provider: script
  script:
    - yarn sign
  on:
    tags: true
  skip_cleanup: true
