env:
  global:
language: node_js
node_js:
- 12
cache:
  yarn: true
script:
  - yarn run lint
  - yarn run crBuild # TODO: build to a different file for CI deployment to CWS
  - yarn run clean
  - yarn run mozBuild
# Deploy update to AMO on tagged builds
deploy:
  provider: script
  script:
    - yarn run mozPublish
  on:
    tags: true
  skip_cleanup: true
